### ISSUE TITLE
Unable to load modules in node_modules

### ISSUE THREAD

**Issue by jwoertink** [opal/opal-node#11]
I'm not able to require node modules in the project directory. 

``` ruby
app = `OpalNode.node_require('express')()`
```

``` text
$ opal-node ./app.rb 

/usr/local/lib/node_modules/opal/lib/opal-node.js:41
      return vm.runInThisContext(js, filename);
                ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Function.require [as node_require] (module.js:380:17)
    at /Users/jeremy/Sites/gamedev/app.rb:6:18
    at /Users/jeremy/Sites/gamedev/app.rb:9:3
    at Function.OpalNode.run (/usr/local/lib/node_modules/opal/lib/opal-node.js:41:17)
    at Function.OpalNode.require (/usr/local/lib/node_modules/opal/lib/opal-node.js:125:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/opal/bin/opal-node:11:10)
    at Module._compile (module.js:456:26)
```

I've tried a few different variations of relative paths, but it's not picking it up. I'm assuming this is due to opal-node being installed globally, and I'm trying to require modules locally.

**Comment by elia** [comment]
Node support is now backed right into opal: `opal -rnodejs -e 'puts "hello node!"'`
